pipeline:
  name: swoop-sidekiq-critical
  identifier: pipeline
  projectIdentifier: SwoopNextGen
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage-sidekiq-critical
        identifier: stagesidekiqcritical
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: stagesidekiqcritical
            serviceInputs:
              serviceDefinition:
                type: ECS
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: stagingcritical
            deployToAll: false
            infrastructureDefinitions:
              - identifier: staging
          execution:
            steps:
              - step:
                  name: ECS Rolling Deploy
                  identifier: ecsRollingDeploy
                  type: EcsRollingDeploy
                  timeout: 10m
                  spec: {}
            rollbackSteps:
              - step:
                  name: ECS Rolling Rollback
                  identifier: ecsRollingRollback
                  type: EcsRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
